### ISSUE TITLE
[배포] AWS EC2, RDS

### ISSUE THREAD

**Issue by ottl-seo** [ottl-seo/GDSC-Recruiting-BE#8]

**Comment by ottlseo** [comment]
RDS 수정 필요 >> 보안 그룹 변경!    

현재 EC2 에서만 접근 가능하도록 되어 있는데 (ottlServerGroup)   
로컬에서 워크벤치로 접근해서 수정할 수 있도록 보안그룹 인바운드 변경하기.
- [x] 완료?
- [x] 다시 안전하게 변경

**Comment by ottlseo** [comment]
## 포트 죽이기

배포하려는데 또!! `Port 8081 was already in use` 오류가 떴다. 

8081 포트(를 잡고있는 프로그램)을 죽여보자.

1. `sudo lsof -i :8081`
2. `sudo kill -9 [PID 번호]`
